### ISSUE TITLE
Кнопка "Добавить" должна блокироваться, когда введена пустая строка

### ISSUE THREAD

**Issue by AndreyTsvetkov** [Fridrirh/sommelier#1]

**Comment by AndreyTsvetkov** [comment]
https://insidejavaee.wordpress.com/2013/09/04/referencing-github-issues-in-commit-messages/ на будущее, можно автоматом линковать коммиты к задачам :)  но ок.

**Comment by BSklyrenko** [comment]
Спасибо! Буду знать)
